---
title: "MCB Consulting Group (MKTG 411)"
subtitle: "Winter 2026"
output: pdf_document
fontsize: 12pt
urlcolor: blue
header-includes:
  - \usepackage{hyperref}
  - \usepackage{multirow}
  - \hypersetup{colorlinks=true, urlcolor=blue}
---

**Meeting Times**: Tuesday and Thursday \vspace{-3mm}

- Section 1: 3:30pm - 4:45pm (170 TNRB)
- Section 2: 12:30pm - 1:45 pm (W110 TNRB)

**CAO**: Cameron Bale \vspace{-3mm}

- Contact: [cameron.bale@byu.edu](mailto:cameron.bale@byu.edu)
- Office Hours (Available Wednesdays, 12pm - 4pm): [By appointment](https://calendly.com/camdbresearch/30min).

**Senior Analytics Partners**: 

- Lark Lapicola \vspace{-3mm}
    - Contact: [artsylar@student.byu.edu](mailto:artsylar@student.byu.edu)
    - Office Hours: 2:00pm - 3:15pm Tu/Th
    
- Vincent Crowns \vspace{-3mm}
    - Contact: [v1842@student.byu.edu](mailto:v1842@student.byu.edu)
    - Office Hours: 1:00pm - 2:15pm M/W (in-person, Blue Line)

- Ethan Miller \vspace{-3mm}
    - Contact: [middlee@student.byu.edu](mailto:middlee@student.byu.edu)
    - Office Hours: 5:00pm - 6:15pm Tu/Th (in-person, Blue Line)
    
- Rebecca Stark \vspace{-3mm}
    - Contact: [rcstark0@student.byu.edu](mailto:rcstark0@student.byu.edu)
    - Office Hours: 11:00am - 12:15pm Tu/Th (in-person, Blue Line)

## Overview

Congratulations on your recent employment with the MCB consulting group! In this job, you will focus on learning and applying the principles and skills central to using analytics to generate marketing insights for clients. Employees are introduced to the fundamentals of using R and will complete a series of projects. This job will build on data analysis techniques used in marketing research (MKTG 401) and introductory business analytics (MSB 325). While prior programming experience is a preferred skill, it is not a requirement.

Job assignments include exercises, quizzes, and projects. Individual study and practice will be crucial to an employee's success. While only a few techniques can be covered during the job, the materials and projects are designed to help equip and direct the interested employee toward the next steps in their mastery of analytics.

### *Job Purpose*

My goal is to help employees to become capable analysts, reflective thinkers, and principled decision makers. Employees will gain experience merging business acumen and technical skills. In doing so, they will become adept in identifying potential solutions to business problems, proposing data-driven approaches to achieve those solutions, and communicating and summarizing technical results in a managerially relevant manner.

### *Training (Learning) Outcomes*

Learning on the job is a two-way street. I will do my best to impart my knowledge and experience to you. By joining this consulting group, you are committing to do your best to show up every day spiritually, mentally, and physically ready to learn and contribute. For those that do, the following outcomes will be attainable: \vspace{-3mm}

- Increased faith in Jesus Christ, by which you will obtain the confidence and courage to not only program in R and conduct analyses, but to communicate results of those analyses in a way that is practical and relevant to business practice.
- The ability to conduct analyses with integrity by clearly documenting decision processes, identifying and communicating flaws in data and models, and quantifying uncertainty.
- Self-motivation to continually improve and to take responsibility for mistakes.
- The ability to recognize and develop excellence in your own analytical work and the work of others.

## Tools and Materials

Throughout this job, you will be analyzing data in R, which is a free, open-source statistical software application that is commonly used in analytics. While it may take some getting used to, fluency in R will provide employees with a marketable and transferable skill.

Each employee will need to come to meetings with a laptop, either their own or one rented from BYU, to code during meetings and complete assignments. All job materials will be available on [Canvas](https://byu.instructure.com). Employees are encouraged to download the job materials so they have access after their employment ends.

### *R*

Employees should use [this link](https://posit.co/download/rstudio-desktop/) to install R and RStudio on their laptops. Note that installing R enables your computer to run R code. RStudio is the application (IDE) by which employees will interact with and write R code.

### *Supplementary Material*

There are two supplementary books that employees may find useful. \vspace{-3mm}

- The first book is *R for Data Science (2e)* by Hadley Wickham and Garrett Grolemund, which is available for free online at [r4ds.hadley.nz](https://r4ds.hadley.nz). This book is particularly helpful for learning more about the [tidyverse](https://www.tidyverse.org).
- The second book is *Tidy Modeling with R* by Max Kuhn and Julia Silge, which is available for free online at [tmwr.org](https://www.tmwr.org). This book is particularly helpful for learning more about [tidymodels](https://www.tidymodels.org).

For those looking for additional practice, there is a community data set and challenge provided each week for [tidytuesday](https://github.com/rfordatascience/tidytuesday).

### *The Internet*

Employees will inevitably end up searching for help online, though it is highly recommended that they search slides, notes, and the supplementary material first. When that fails, the [Posit Community](https://community.rstudio.com) and [Stack Overflow](http://stackoverflow.com), in that order, will be most helpful to push through inevitable roadblocks. Please note that employees will be evaluated on their use of the tools and coding style covered during job meetings and there is no guarantee that any help online will satisfy this expectation.

### *Artificial Intelligence*

Artificial intelligence (AI) has become an indispensable tool for data science and analytics. As such, it is expected that employees will leverage AI capabilities in *understanding* and *writing* code. It is also expected that employees will *regulate* their own AI usage. [Early-stage research](https://arxiv.org/pdf/2506.08872v1) suggests that active ChatGPT usage can reduce learning skills, reflected in lower amounts of brain activity when performing tasks such as writing (or coding!). This represents a danger to the personal and spiritual growth of employees, but at the same time, we should seek to make the firm as productive as possible.

The gospel always provides the necessary context for us to reconcile conflicting temporal and spiritual motivations. The following excerpt from ["Things as They Really Are 2.0"](https://www.churchofjesuschrist.org/study/broadcasts/worldwide-devotional-for-young-adults/2024/11/13bednar?lang=eng) gives some excellent perspective:

"Now, I believe AI appropriately can assist in gathering information, critiquing our thinking, evaluating our writing style, and accelerating an iterative process of learning “line upon line [and] precept upon precept.” But the divine capacities to create and work belong uniquely to each of us as sons and daughters of God. We undoubtedly can generate and produce fabulous content for [school/church/work] with AI. But the objective is not merely producing or presenting impressive content; rather, it is working and becoming what God intends and yearns for us to become."

I encourage you to keep the following principles in mind:

- AI is a *tool*, and is not good and bad in and of itself; its morality depends on how it is used. AI can assist in gathering information, critiquing thinking, and evaluating writing and coding, but it is not a source of truth and cannot replace personal revelation.
- Over-reliance on AI can lead to both spiritual and temporal slothfulness. Our objective is not just the final product, but the process of working and learning line upon line and becoming the person God intends us to be.
- AI cannot simulate, imitate, or replace the influence of the Holy Ghost. Spiritual discernment is essential when navigating content and uncovering truth.
- AI should supplement, not replace, human work, creativity, and divine capacities.

Remember - do not be "transformed from [employees] who can act into objects that are only acted upon."

## Employee Success

Because of our focus on learning to use a programming language to analyze data, the **beginning of your employment has a steep learning curve (lots of material in a short amount of time)** and employees should plan accordingly.

Employees should consider the following tips for enhancing their job performance. \vspace{-3mm}

1. Seek learning by study and faith (D&C 109:7).
2. Prepare for job meetings by previewing material and coming with questions.
3. Actively code, take notes, and ask questions.
4. Practice coding by completing exercises, referencing supplementary material as needed.
5. Review exercise solutions and note where and why your work differs.
6. Use the quizzes to gauge how well the material is understood.
7. Work with other employees and utilize office hours.
8. Download and organize all job materials, notes, and code.

### *Coding*

Employees should consider the following coding tips. \vspace{-3mm}

1. Learn by doing: Code live during meetings and complete exercises.
2. Pay *careful* attention to details.
3. Don't code from scratch. Start with previous work and solutions.
4. Look at and emulate good code.
5. Literally sketch what transformed data should look like in the end.

## Assessment

### Performance Assessment (Grading) Philosophy

Unfortunately, performance assessments will almost always involve some level of subjectivity. I have taken steps to make the assessments as fair as possible. Please see the approaches for assessing the quality of the three types of deliverables you will produce:

- Skill-building exercises: employees evaluate their own exercises according to a provided rubric.
- Knowledge Checks: multiple choice questions that are automatically graded in Canvas.
- Projects: open ended projects that are evaluated once by each senior partner. Employees receive the average of the partner assessments as their final evaluation for a given project. To encourage personal progress and growth, we will give a boost to any employee that demonstrates improvement in project quality of the course of their employment.

Final performance assessments will follow a standard rubric. As mandated, the distribution of employee grades will result in no more than an A- average (*i.e.*, a 3.65 GPA).

|    |         |    |        |    |        |
| :- | :------ | :- | :----- | :- | :----- |
| A  | 93-100% | B- | 80-82% | D+ | 67-69% |
| A- | 90-92%  | C+ | 77-79% | D  | 63-66% |
| B+ | 87-89%  | C  | 73-76% | D- | 60-62% |
| B  | 83-86%  | C- | 70-72% | E  | 0-59%  |

Final grades will be determined based on the following weights applied to the evaluations of each type of deliverable.

|                                              |     |
| :------------------------------------------- | :-: |
| Exercises                                    | 20% |
| Quizzes                                      | 30% |
| Projects                                     | 50% |

Employees have the opportunity to submit any **Skill-building exercise** late for up to *one week* after the initial deadline, for 75% credit (*i.e.*, you will scale your score by 0.75). In addition, if your first score on an **Exercise** is less than 75%, you may resubmit once to receive 75% credit. Note that only two submissions will be accepted for any **Exercise**. **Knowledge Checks** and **Projects** may not be submitted late except under prior authorization from the instructor.

### *Skill-building Exercises*

Each job meeting ends with a skill-building exercise that must be submitted prior to the start of the next meeting. While employees are encouraged to work together, each employee is required to submit their own exercise.

Employees will evaluate their own submitted exercises using a rubric specified in each posted exercise solution, adding comments (directly for R scripts or using the comment feature for Word documents) where their solution differs from the posted solution.

After each unit, employees will submit all of their previously submitted but now graded exercises, with comments, along with responses to specified prompts as part of that unit's exercise review. **Late submissions that are submitted after their corresponding unit should be graded at the time of submission. Employees must notify the CAO at the time of submission of such an assignment.**

### *Knowledge Checks*

Knowledge checks consist of multiple choice questions administered via Canvas. The purpose is to gauge the overall comprehension of important analytics concepts and methods. Employees must complete quizzes individually, without assistance from other classmates (although the use of AI, job notes, etc. is acceptable). Each knowlege check will be available on Canvas during the associated unit.

### *Projects*

The projects are the culmination of each unit. Employees will be presented with a data set and a list of business problems proposed by a client. Employees will have a week to complete the project, in which they will produce a technical report and an executive summary detailing their results and recommendations for the client. While employees can work together in small groups, each employee is required to submit their own work. Projects that are identical (or highly similar) will be flagged and potentially penalized. Employees are expected to attend job meetings during project weeks where they can ask the CAO and senior partners questions and work in groups. Employees will also be required to provide project feedback to one other employee, documenting the strengths of the project and any recommended changes or additions. Finally, each senior partner will have the opportunity to choose a project they believe exceeds expectations, and the corresponding employees will receive an extra commendation.

### *Extra Commendations*

Employees interested in earning extra commendations (and supporting overall firm cohesiveness) may earn one additional point towards their lowest project by meeting with the CAO for a one-on-one 'get-to-know-you' office hours meeting. Remember that office hours are subject to availability. See the link at the top of the syllabus for scheduling.

## Schedule

All deliverables are due on Canvas at the start of the meeting they are associated with in the schedule. The third review and the third project will be due by the end of finals.

Please note that the CAO reserves the right to change the syllabus and company policies regarding AI usage, performance assessments, etc., including the schedule, at any time and for any reason. In such circumstances, the CAO will provide employees sufficient advance notice as it relates to deliverable deadlines.

\begin{center}
\footnotesize
\renewcommand{\arraystretch}{1.1}
\begin{tabular}{| c | c | l | l |}
\hline
\textbf{Week} & \textbf{Unit} & \textbf{Topic} & \textbf{Due Dates}\\

% Data
\hline
\multirow{3}{*}{\shortstack{Week 1 \\ January 8}}
  & \multirow{15}{*}{\shortstack{Data}}
	  & \multirow{3}{*}{\shortstack[l]{FAQ and the Analytics Process}}	
	    & \multirow{3}{*}{}\\ 	
	& & & \\
	& & & \\

\cline{1-1}\cline{3-4}
\multirow{3}{*}{\shortstack{Week 2 \\ January 13, 15}}
	& & \multirow{3}{*}{\shortstack[l]{R and Transforming Data \\ Visualize Discrete Data\textcolor{white}{g}}} 
	  & \multirow{3}{*}{\shortstack[l]{Exercise 1 (T) \\ Exercise 2 (Th)}}\\
	& & & \\
	& & & \\

\cline{1-1}\cline{3-4}
\multirow{3}{*}{\shortstack{Week 3 \\ January 20, 22}}
	& & \multirow{3}{*}{\shortstack[l]{Visualize Continuous Data \\ Quarto and Tidy Data}}
		& \multirow{3}{*}{\shortstack[l]{Exercise 3 (T) \\ Exercise 4 (Th)}} \\
  & & & \\
  & & & \\

\cline{1-1}\cline{3-4}
\multirow{3}{*}{\shortstack{Week 4 \\ January 27, 29}}
	& & \multirow{3}{*}{\shortstack[l]{Database Queries \\ APIs and Dashboards}}
		& \multirow{3}{*}{\shortstack[l]{Exercise 5 (T) \\ Exercise 6 (Th)}} \\
  & & & \\
  & & & \\

\cline{1-1}\cline{3-4}
\multirow{3}{*}{\shortstack{Week 5 \\ February 3, 5}}
	& & \multirow{3}{*}{\shortstack[l]{\textbf{Project 1: Patagonia CRM}}}
		& \multirow{3}{*}{\shortstack[l]{Exercise 7, Quiz 1 (T)}} \\
	&	& & \\
  &	& & \\

% Inference
\hline
\multirow{3}{*}{\shortstack{Week 6 \\ February 10, 12}}
  & \multirow{15}{*}{\shortstack{Inference}}
    & \multirow{3}{*}{\shortstack[l]{R and Statistical Modeling \\ Linear Models}}
	    & \multirow{3}{*}{\shortstack[l]{Review 1, Project 1 (T) \\ Exercise 8 (Th)}} \\
	& & & \\
	& & & \\

\cline{1-1}\cline{3-4}
\multirow{3}{*}{\shortstack{Week 7 \\ February 19}}
	& & \multirow{3}{*}{\shortstack[l]{Evaluate Model Fit}}
		& \multirow{3}{*}{\shortstack[l]{Exercise 9 (Th)}} \\
	&	& & \\
  &	& & \\

\cline{1-1}\cline{3-4}
\multirow{3}{*}{\shortstack{Week 8 \\ February 24, 26}}
	& & \multirow{3}{*}{\shortstack[l]{Explanatory Variables \\ Overfitting and Prediction}}
		& \multirow{3}{*}{\shortstack[l]{Exercise 10 (T) \\ Exercise 11 (Th)}} \\
	&	& & \\
  &	& & \\

\cline{1-1}\cline{3-4}
\multirow{3}{*}{\shortstack{Week 9 \\ March 3, 5}}
	&	& \multirow{3}{*}{\shortstack[l]{Preprocess Data \\ Logistic Regression}}
		& \multirow{3}{*}{\shortstack[l]{Exercise 12 (T) \\ Exercise 13 (Th)}}\\
	&	& & \\
  &	& & \\

\cline{1-1}\cline{3-4}
\multirow{3}{*}{\shortstack{Week 10 \\ March 10, 12}}
	& & \multirow{3}{*}{\shortstack[l]{\textbf{Project 2: Nielsen Sales}}}
		& \multirow{3}{*}{\shortstack[l]{Exercise 14, Quiz 2 (T)}} \\
	&	& & \\
  &	& & \\

% Prediction
\hline
\multirow{3}{*}{\shortstack{Week 11 \\ March 17, 19}}
	& \multirow{15}{*}{\shortstack{Prediction}} 	
		& \multirow{3}{*}{\shortstack[l]{R and Machine Learning \\ Decision Trees}}
			& \multirow{3}{*}{\shortstack[l]{Review 2, Project 2 (T) \\ Exercise 15 (Th)}}\\
	&	& & \\
  &	& & \\

\cline{1-1}\cline{3-4}
\multirow{3}{*}{\shortstack{Week 12 \\ March 24, 26}} 	
	&	& \multirow{3}{*}{\shortstack[l]{Random Forests\textcolor{white}{g} \\ Deep Learning}}
		& \multirow{3}{*}{\shortstack[l]{Exercise 16 (T) \\ Exercise 17 (Th)}}\\
	&	& & \\
  &	& & \\

\cline{1-1}\cline{3-4}
\multirow{3}{*}{\shortstack{Week 13 \\ March 31, April 2}}
	&	& \multirow{3}{*}{\shortstack[l]{Ensembles\textcolor{white}{g} \\ K-Means Clustering}} 
		& \multirow{3}{*}{\shortstack[l]{Exercise 18 (T) \\ Exercise 19 (Th)}}\\
	&	& & \\
  &	& & \\

\cline{1-1}\cline{3-4}
\multirow{3}{*}{\shortstack{Week 14 \\ April 7, 9}}
	&	& \multirow{3}{*}{\shortstack[l]{Hierarchical Clustering \\ Topic Models}} 
		& \multirow{3}{*}{\shortstack[l]{Exercise 20 (T) \\ Exercise 21 (Th)}}\\
	&	& & \\
  &	& & \\

\cline{1-1}\cline{3-4}
\multirow{3}{*}{\shortstack{Week 15 \\ April 14}}
	& & \multirow{3}{*}{\shortstack[l]{\textbf{Project 3: Roomba Survey}}}
		& \multirow{3}{*}{\shortstack[l]{Exercise 22, Quiz 3 (T)}} \\
	&	& & \\
  &	& & \\

\hline
\end{tabular}\\
\end{center}

\newpage

## Honor Code

In keeping with the principles of the BYU Honor Code, employees are expected to be honest in all of their work. Academic honesty means, most fundamentally, that any work you present as your own must in fact be your own work and not that of another. Violations of this principle may result in a failing grade on the deliverable and/or in the course and additional disciplinary action by the university. Employees are also expected to adhere to the Dress and Grooming Standards. Adherence demonstrates respect for yourself and others and ensures an effective learning and working environment. It is the university's expectation, and every instructor's expectation, that each student will abide by all Honor Code standards. Please call the Honor Code Office at 801-422-2847 if you have questions about those standards.

## Preventing & Responding to Sexual Misconduct

Brigham Young University prohibits all forms of sexual harassment -- including sexual assault, dating violence, domestic violence, and stalking on the basis of sex -- by its personnel and students and in all its education programs or activities. University policy requires all faculty members to promptly report incidents of sexual harassment that come to their attention in any way and encourages reports by students who experience or become aware of sexual harassment. Incidents should be reported to the Title IX Coordinator at [title9@byu.edu](mailto:title9@byu.edu) or 801-422-8692 or 1085 WSC. Reports may also be submitted online at [titleix.byu.edu/report](https://titleix.byu.edu/report) or 1-888-238-1062 (24-hours a day). BYU offers a number of resources and services for those affected by sexual harassment, including the university's confidential Sexual Assault Survivor Advocate. Additional information about sexual harassment, the university's Sexual Harassment Policy, reporting requirements, and resources can be found in the University Catalog, by visiting [titleix.byu.edu](http://titleix.byu.edu), or by contacting the university's Title IX Coordinator.

## Student Disability

Brigham Young University is committed to providing a working and learning atmosphere that reasonably accommodates qualified persons with disabilities. A disability is a physical or mental impairment that substantially limits one or more major life activities. Whether an impairment is substantially limiting depends on its nature and severity, its duration or expected duration, and its permanent or expected permanent or long-term impact. Examples include vision or hearing impairments, physical disabilities, chronic illnesses, emotional disorders (*e.g.*, depression, anxiety), learning disorders, and attention disorders (*e.g.*, ADHD). If you have a disability which impairs your ability to complete this course successfully, please contact the University Accessibility Center (UAC), 2170 WSC or 801-422-2767 to request a reasonable accommodation. The UAC can also assess students for learning, attention, and emotional concerns. If you feel you have been unlawfully discriminated against on the basis of disability, please contact Shawn Smith at the Equal Employment Office at 801-422-2845, D-276 ASB for help.

## Inappropriate Use of Course Materials

All course materials (*e.g.*, outlines, handouts, syllabi, exams, quizzes, PowerPoint presentations, lectures, audio and video recordings, etc.) are proprietary. Students are prohibited from posting or selling any such course materials without the express written permission of the professor teaching this course. To do so is a violation of the Brigham Young University Honor Code.

## Academic Honesty

One of the injunctions of the Honor Code is the call to "be honest." Students come to the university not only to improve their minds, gain knowledge, and develop skills that will assist them in their life's work, but also to build character. "President David O. McKay taught that character is the highest aim of education..." (The Aims of a BYU Education). It is the purpose of the BYU Academic Honesty Policy to assist in fulfilling that aim. BYU students should seek to be totally honest in their dealings with others. They should complete their own work and be evaluated based upon that work. They should avoid academic dishonesty and misconduct in all its forms, including but not limited to plagiarism, fabrication or falsification, cheating, and other academic misconduct.

## Marriott School of Business Inclusion Statement

BYU Marriott is committed to fostering an environment of belonging for all students and employees. In accordance with the BYU Marriott vision, mission, and values, “We value respect for all individuals as children of God and recognize the inherent worth, divine potential, and agency of each person. A climate of respect and belonging enhances our learning, facilitates collaboration, and encourages personal growth.”

We embrace the statement President Russell M. Nelson made on June 1, 2020.

*"The Creator of us all calls on each of us to abandon attitudes of prejudice against any group of God's children. Any of us who has prejudice toward another race needs to repent!*

*During the Savior's earthly mission, He constantly ministered to those who were excluded, marginalized, judged, overlooked, abused, and discounted. As His followers, can we do anything less?*

*Let us be clear. We are brothers and sisters, each of us the child of a loving Father in Heaven. His Son, the Lord Jesus Christ, invites all to come unto Him -- 'black and white, bond and free, male and female,' (2 Nephi 26:33). It behooves each of us to do whatever we can in our spheres of influence to preserve the dignity and respect every son and daughter of God deserves."*

## Mental Health

Mental health concerns and stressful life events can affect students' academic performance and quality of life. BYU Counseling and Psychological Services (CAPS, 1500 WSC, 801-422-3035, caps.byu.edu) provides individual, couples, and group counseling, as well as stress management services. These services are confidential and are provided by the university at no cost for full-time students. For general information please visit [caps.byu.edu](https://caps.byu.edu); for more immediate concerns please visit [help.byu.edu](http://help.byu.edu).

